name: mlflow-conda
channels:
  - defaults

dependencies:
  # ---- Python ----
  - python=3.12.3

  # ---- Core numerical stack (conda handles these better) ----
  - numpy=2.4.0
  - pandas=2.3.3
  - scipy=1.16.3
  - scikit-learn=1.8.0
  - matplotlib=3.10.8
  - pyarrow=22.0.0
  - pillow=12.0.0
  - h5py=3.15.1

  # ---- Runtime / build essentials ----
  - pip
  - setuptools=80.9.0
  - wheel=0.45.1

  # ---- Everything else via pip (by design) ----
  - pip:
    # ===== ML / DL =====
    - tensorflow==2.20.0
    - keras==3.13.0
    - tensorboard==2.20.0
    - tensorboard-data-server==0.7.2
    - ml_dtypes==0.5.4
    - opt_einsum==3.4.0
    - optree==0.18.0
    - flatbuffers==25.12.19
    - gast==0.7.0
    - google-pasta==0.2.0
    - astunparse==1.6.3
    - libclang==18.1.1
    - termcolor==3.2.0
    - wrapt==2.0.1
    - absl-py==2.3.1
    - grpcio==1.76.0
    - protobuf==6.33.2

    # ===== MLflow =====
    - mlflow==3.8.0
    - mlflow-skinny==3.8.0
    - mlflow-tracing==3.8.0
    - databricks-sdk==0.76.0
    - docker==7.1.0
    - cloudpickle==3.1.2
    - gitpython==3.1.45
    - gitdb==4.0.12
    - smmap==5.0.2
    - sqlparse==0.5.5
    - sqlalchemy==2.0.45
    - alembic==1.17.2
    - greenlet==3.3.0

    # ===== Web / API =====
    - fastapi==0.127.0
    - starlette==0.50.0
    - uvicorn==0.40.0
    - gunicorn==23.0.0
    - flask==3.1.2
    - flask-cors==6.0.2
    - click==8.3.1
    - blinker==1.9.0
    - itsdangerous==2.2.0
    - jinja2==3.1.6
    - markupsafe==3.0.3
    - werkzeug==3.1.4

    # ===== Networking / HTTP =====
    - requests==2.32.5
    - urllib3==2.6.2
    - certifi==2025.11.12
    - charset-normalizer==3.4.4
    - idna==3.11
    - h11==0.16.0
    - anyio==4.12.0

    # ===== Auth / Security =====
    - cryptography==46.0.3
    - cffi==2.0.0
    - pycparser==2.23
    - rsa==4.9.1
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.2
    - google-auth==2.45.0
    - cachetools==6.2.4

    # ===== OpenTelemetry =====
    - opentelemetry-api==1.39.1
    - opentelemetry-sdk==1.39.1
    - opentelemetry-proto==1.39.1
    - opentelemetry-semantic-conventions==0.60b1

    # ===== GraphQL =====
    - graphene==3.4.3
    - graphql-core==3.2.7
    - graphql-relay==3.2.0

    # ===== Utils / Formatting =====
    - python-dotenv==1.2.1
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - tzdata==2025.3
    - pyyaml==6.0.3
    - packaging==25.0
    - six==1.17.0
    - rich==14.2.0
    - pygments==2.19.2
    - markdown==3.10
    - markdown-it-py==4.0.0
    - mdurl==0.1.2
    - fonttools==4.61.1
    - contourpy==1.3.3
    - cycler==0.12.1
    - kiwisolver==1.4.9
    - pyparsing==3.2.5

    # ===== Misc =====
    - annotated-types==0.7.0
    - annotated-doc==0.0.4
    - importlib-metadata==8.7.1
    - typing-extensions==4.15.0
    - typing-inspection==0.4.2
    - zipp==3.23.0
    - huey==2.5.5
    - joblib==1.5.3
    - namex==0.1.0
